version: "3"

services:
  postgres:
    image: "postgres:11"
    container_name: delivery-DB
    command:
      - "postgres"
      - "-c"
      - listen_addresses="*"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
      
volumes:
  postgres: